services:
  subscription_db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: golang:1.23-alpine
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - subscription_db
    ports:
      - "8080:8080"
    command: go run cmd/api/main.go

volumes:
  db_data: